---
groups:
- name: main
  jobs:
  - build-and-verify
  - deploy
  - provision
- name: versioning
  jobs:
  - increase-minor
  - increase-major

resource_types:
- name: maven-resource
  type: docker-image
  source:
    repository: pivotalpa/maven-resource
    tag: 1.3.2

#- name: email
#  type: docker-image
#  source:
#    repository: mdomke/concourse-email-resource
  
resources:   

- name: pipeline
  type: git
  source:
    uri: (( grab pipeline.source.uri ))
    branch: (( grab pipeline.source.branch ))
    private_key: (( grab pipeline.source.private_key ))

- name: source-code
  type: git
  source:
    uri: (( grab app.source.uri ))
    branch: (( grab app.source.branch ))
    private_key: (( grab app.source.private_key ))
    ignore_paths:
      - version

- name: version
  type: semver
  source:
    driver: git
    initial_version: (( grab app.initial_version ))
    uri: (( grab app.source.uri ))
    private_key: (( grab app.source.private_key ))
    branch: (( grab app.source.branch ))
    file: version

- name: artifact-repo
  type: maven-resource
  source:
    url: (( grab pipeline.repository.uri ))
    artifact: (( grab app.artifact ))
    username: (( grab pipeline.repository.username ))
    password: (( grab pipeline.repository.password ))

- name: pcf-dev
  type: cf
  source:
    api: (( grab deployment.dev.pcf.api ))
    username: (( grab deployment.dev.pcf.username ))
    password: (( grab deployment.dev.pcf.password ))
    organization: (( grab deployment.dev.pcf.organization ))
    space: (( grab deployment.dev.pcf.space ))
    skip_cert_check: (( grab deployment.dev.pcf.skip_cert_check ))

#- name: release-announcement
#  type: email
#  source:
#    from: (( grab pipeline.emailAddress ))

jobs:
- name: build-and-verify
  plan:
  - get: source-code
    trigger: true
  - get: pipeline
  - get: version
  - task: build-and-verify
    file: pipeline/tasks/build.yml
  - put: artifact-repo
    params:
      file: build-artifact/*.jar
      pom_file: source-code/pom.xml

- name: provision
  disable_manual_trigger: true
  plan:
  - get: artifact-repo
    passed: [build-and-verify]
  - get: pipeline
  - task: apply
    file: pipeline/tasks/terraform.yml
    input_mapping: {artifact: artifact-repo}
    params:
      TF_VAR_api_url: (( grab deployment.dev.pcf.api ))
      TF_VAR_user: (( grab deployment.dev.pcf.username ))
      TF_VAR_password: (( grab deployment.dev.pcf.password ))
      TF_VAR_org: (( grab deployment.dev.pcf.organization ))
      TF_VAR_space: (( grab deployment.dev.pcf.space ))
          
- name: deploy
  disable_manual_trigger: true
  plan:
  - get: artifact-repo
    trigger: true
    passed: [provision]
  - get: pipeline
  - get: source-code
  - task: generate-manifest
    file: pipeline/tasks/generate-manifest.yml
    input_mapping: {artifact: artifact-repo}
    params:
      APP_NAME: (( grab app.name ))
      APP_HOST: (( grab deployment.dev.pcf.host ))
      APP_DOMAIN: (( grab deployment.dev.pcf.domain ))
  - put: pcf-dev
    params:
      manifest: manifest/manifest.yml

- name: increase-major
  serial: true
  plan:
  - put: version
    params: { bump: major }

- name: increase-minor
  serial: true
  plan:
  - put: version
    params: { bump: minor }
