platform: linux
image_resource:
  type: docker-image
  source:
    repository: maven
    tag: 3.3.9-jdk-8
inputs:
  - name: pipeline
  - name: source-code
  - name: version
outputs:
  - name: build-artifact
run:
  path: pipeline/tasks/build.sh
