platform: linux
image_resource:
  type: docker-image
  source:
    repository: concourse/buildroot
    tag: git
inputs:
  - name: pipeline
  - name: version
  - name: deployment-manifest
outputs:
  - name: deployment-manifest-updated
params: 
  MANIFEST_FILE: 

run:
  path: pipeline/tasks/promote-release.sh
