platform: linux
image_resource:
  type: docker-image
  source:
    repository: marcialfrg/terraform
    # TODO PUT A TAG
inputs:
  - name: pipeline
  - name: source-code
run:
  path: pipeline/tasks/terraform.sh
